// redux
import { Provider } from "react-redux";
import Store from "../../RTK/store/store";
import '../app/globals.css';
import '../components/CustomRadio/CustomRadio.css'
import '../components/ToggleSwitch/ToggleSwitch.css'
import Head from "next/head";
import Footer from '../components/Footer'

function MyApp({ Component, pageProps }) {
    return (
        <>
            <Head>
                <title>Fatayeralaaltayer</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <Provider store={Store}>

                <Component {...pageProps} />
                <Footer />
            </Provider>
        </>
    );
}

export default MyApp;

